version: '3.9'
services:
   db:
     image: gabume/mysql:latest
     volumes:
       - db_data:/var/lib/mysql

   wordpress:
     depends_on:
       - db
     image: gabume/wordpress:latest
     ports:
       - "80:80"
     environment:
       WORDPRESS_DB_HOST: db:3306
volumes:
  db_data: